#!/bin/bash
#SBATCH --job-name=distantly_supervised_dataset
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --mail-type=END
#SBATCH --mail-user=ragger.jonkers@student.uva.nl

module purge
module load 2019
module load CUDA/10.1.243
module load Anaconda3/2018.12

source activate lisaenv

RUN_NAME="`date +%d_%m_%Y_%H_%M_%S`";
for i in 0.7 0.72 0.74 0.76 0.78 0.8 0.82 0.84 0.86 0.88 0.9 0.92 0.94 0.96 0.98 1.0
do
    echo $i
done
wait


